### ISSUE TITLE
[BUG] can not successful build 

### ISSUE THREAD

**Issue by lecheel** [waylyrics/waylyrics#274]
\* Version of WayLyrics: 
commit c37d17e66c3f408efca9a4abb079f042731e92f7 (HEAD -> master, tag: v0.3.18, origin/master, origin/HEAD)
ubuntu 22.04 
rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball)
Steps to Reproduce:
> Describe the steps to reproduce the issue
> cargo build --release --locked --target-dir target

Actual Behavior:
> Describe what actually happened
   Compiling gdk4 v0.9.4
   Compiling gsk4 v0.9.4
   Compiling gtk4 v0.9.4
error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/lyric_providers/lrclib/mod.rs:1:11
  |
1 | use std::{sync::LazyLock, time::Duration};
  |           ^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/lyric_providers/lrclib/mod.rs:15:31
   |
15 | pub static LRCLIB_API_CLIENT: LazyLock<LRCLibAPI> = LazyLock::new(Default::default);
   |                               ^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/lyric_providers/lrclib/mod.rs:15:53
   |
15 | pub static LRCLIB_API_CLIENT: LazyLock<LRCLibAPI> = LazyLock::new(Default::default);
   |                                                     ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/lyric_providers/lrclib/mod.rs:16:28
   |
16 | pub static REQWEST_CLIENT: LazyLock<Client> = LazyLock::new(Default::default);
   |                            ^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/lyric_providers/lrclib/mod.rs:16:47
   |
16 | pub static REQWEST_CLIENT: LazyLock<Client> = LazyLock::new(Default::default);
   |                                               ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/lyric_providers/lrclib/mod.rs:15:53
   |
15 | pub static LRCLIB_API_CLIENT: LazyLock<LRCLibAPI> = LazyLock::new(Default::default);
   |                                                     ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/lyric_providers/lrclib/mod.rs:16:47
   |
16 | pub static REQWEST_CLIENT: LazyLock<Client> = LazyLock::new(Default::default);
   |                                               ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `waylyrics` (lib) due to 7 previous errors
Logs from WayLyrics:

**Comment by mokurin000** [comment]
@lecheel 上个commit使用了lazy_cell，那个是比较新的Rustc才稳定的...
我换下once_cell的东西

**Comment by lecheel** [comment]
thanks @mokurin000 after update rustc to 1.85 everything is good
